name: Publish

on:
  workflow_dispatch:

jobs:
  run-publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.1'

      - name: Bundle install
        run: |
          bundle install
        shell: bash

      - name: Pod Lib Lint
        run: |
          bundle exec fastlane pod_lint

      - name: Publish to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          bundle exec fastlane publish_to_cocoapods
